easy_admin:
    site_name: Symfony certification preparation

    design:
        menu:
            - { route: 'homepage' , label: 'Back to the website', icon: 'home' }
            - { entity: 'Conference', label: 'Conferences', icon: 'map-marker' }
            - { entity: 'Comment', label: 'Comments', icon: 'comments' }
            - { entity: 'Question', label: 'Questions', icon: 'question' }
            - { entity: 'Category', label: 'Categories', icon: 'sticky-note' }

    entities:
        # List the entity class name you want to manage
        Conference:
            class: App\Entity\Conference

        Comment:
            class: App\Entity\Comment
            list:
                fields:
                    - author
                    - { property: 'email', type: 'email' }
                    - { property: 'createdAt', type: 'datetime' }
                sort: ['createdAt', 'ASC']
                filters: ['conference']
            edit:
                fields:
                    - { property: 'conference' }
                    - { property: 'createdAt', type: datetime, type_options: { disabled: true } }
                    - 'author'
                    - { property: 'email', type: 'email' }
                    - text

        Question:
            class: App\Entity\Question
            list:
                filters: ['category']

        Category:
            class: App\Entity\Category

        Domain:
            class: App\Entity\Domain

#        - App\Entity\User
